'use client';
import {useCallback,useEffect,useState} from 'react';
import {supabase} from '@/lib/supabaseClient';
import {useCodmAuth} from '@/lib/authRoles';

type Season={id:string;name:string;is_active:boolean;is_historical:boolean;starts_on:string|null;ends_on:string|null;description:string|null};
export default function SeasonsAdminPage(){
 const auth=useCodmAuth();const [seasons,setSeasons]=useState<Season[]>([]);const [busy,setBusy]=useState(false);
 const [error,setError]=useState('');const [name,setName]=useState('');const [historical,setHistorical]=useState(true);
 const [from,setFrom]=useState('');const [to,setTo]=useState('');const [description,setDescription]=useState('');
 const load=useCallback(async()=>{const {data,error}=await supabase.from('codm_seasons').select('*').order('created_at',{ascending:false});if(error)setError(`Impossibile leggere stagioni: ${error.message}. Esegui la migrazione V14.1.`);else setSeasons(data as Season[]);},[]);
 useEffect(()=>{void load()},[load]);
 async function run(task:()=>Promise<{error?:{message:string}|null}>,success:string){setBusy(true);setError('');try{const r=await task();if(r.error)throw new Error(r.error.message);setError(success);await load()}catch(e){setError(e instanceof Error?e.message:'Operazione fallita')}finally{setBusy(false)}}
 if(auth.loading)return <main className="container"><p>Verifica account...</p></main>;
 if(auth.role!=='owner')return <main className="container"><section className="card"><h1>Gestione stagioni riservata all’Admin principale</h1></section></main>;
 return <main className="container wide ak-v14"><section className="card gaming-panel"><p className="eyebrow">AK47DX • V14</p><h1>Gestione stagioni</h1><p className="muted">Crea stagioni storiche senza toccare la stagione attiva. Attivando una stagione ordinaria, le prossime partite saranno associate automaticamente alla nuova stagione. Le partite già salvate non vengono spostate.</p>{error&&<div className="notice" role="status">{error}</div>}</section>
 <section className="grid grid-2 top-gap"><div className="card"><h2>Stagioni salvate</h2><div className="v14-season-list">{seasons.map(s=><div key={s.id} className="v14-season-row"><div><b>{s.name}</b><div className="muted">{s.starts_on||'Senza data'} — {s.ends_on||'aperta'} · {s.is_historical?'Archivio storico':'Stagione normale'}</div></div><div className="cal-buttons">{s.is_active?<span className="v14-pill pass">Attiva</span>:<>{!s.is_historical&&<button className="btn small secondary" disabled={busy} onClick={()=>{if(window.confirm(`Attivare ${s.name}? Le partite precedenti non cambiano.`))void run(()=>supabase.rpc('ak47dx_admin_activate_season',{p_season_id:s.id}),`${s.name} attivata.`)}}>Attiva</button>}<button className="btn small secondary" disabled={busy} onClick={()=>void run(()=>supabase.rpc('ak47dx_admin_set_historical',{p_season_id:s.id,p_historical:!s.is_historical}),`Tipo stagione aggiornato.`)}>{s.is_historical?'Rendi attivabile':'Archivia'}</button></>}</div></div>)}{!seasons.length&&<p className="muted">Nessuna stagione caricata.</p>}</div></div>
 <div className="card"><h2>Nuova stagione</h2><div className="form"><div className="field"><label>Nome</label><input className="input" value={name} onChange={e=>setName(e.target.value)} placeholder="Stagione 2025 / Stagione 3"/></div><div className="field"><label>Destinazione</label><select className="select" value={historical?'historical':'normal'} onChange={e=>setHistorical(e.target.value==='historical')}><option value="historical">Archivio storico (non attiva automaticamente)</option><option value="normal">Nuova stagione da attivare successivamente</option></select></div><div className="grid grid-2"><div className="field"><label>Inizio (facoltativo)</label><input className="input" type="date" value={from} onChange={e=>setFrom(e.target.value)}/></div><div className="field"><label>Fine (facoltativo)</label><input className="input" type="date" value={to} onChange={e=>setTo(e.target.value)}/></div></div><div className="field"><label>Descrizione (facoltativa)</label><input className="input" value={description} onChange={e=>setDescription(e.target.value)}/></div><button className="btn" disabled={busy||name.trim().length<2} onClick={()=>void run(async()=>{const r=await supabase.rpc('ak47dx_admin_create_season',{p_name:name.trim(),p_historical:historical,p_start:from||null,p_end:to||null,p_description:description||null});if(!r.error){setName('');setDescription('');setFrom('');setTo('')}return r},'Stagione creata. Puoi selezionarla nelle importazioni storiche.')}>+ Crea stagione</button></div></div></section></main>;
}
